package com.cdyne.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-06-29T16:12:07.175+03:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://ws.cdyne.com/", name = "IP2GeoSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface IP2GeoSoap {

    /**
     * Use a License Key of 0 for Testing
     */
    @WebMethod(operationName = "ResolveIP", action = "http://ws.cdyne.com/ResolveIP")
    @RequestWrapper(localName = "ResolveIP", targetNamespace = "http://ws.cdyne.com/", className = "com.cdyne.ws.ResolveIP")
    @ResponseWrapper(localName = "ResolveIPResponse", targetNamespace = "http://ws.cdyne.com/", className = "com.cdyne.ws.ResolveIPResponse")
    @WebResult(name = "ResolveIPResult", targetNamespace = "http://ws.cdyne.com/")
    public com.cdyne.ws.IPInformation resolveIP(
        @WebParam(name = "ipAddress", targetNamespace = "http://ws.cdyne.com/")
        java.lang.String ipAddress,
        @WebParam(name = "licenseKey", targetNamespace = "http://ws.cdyne.com/")
        java.lang.String licenseKey
    );
}
